### ISSUE TITLE
Design consistency & syntax

### ISSUE THREAD

**Issue by BrendaHoyle** [jammiemountz/petbot-webapp#18]
There's an inconsistency in syntax in the features section:

The "treat them" feature in the middle has a period while the other two don't.

**Comment by BrendaHoyle** [comment]
There's an inconsistency in syntax in the features section: 

The "treat them" feature in the middle has a period while the other two don't.

**Comment by BrendaHoyle** [comment]
"Learn more about the PetBot Team." should be a link since it's asking visitors to do something, but it sounds like it's misplaced text.

**Comment by BrendaHoyle** [comment]
Typo in "We’ve got animal instincts" text. Replace "to" (bolded) in the second setence to "the":

PetBot started in 2015 with the realization that we have no idea what our pets are doing while we're gone — and that made us sad. Fast forward to now, we’re reshaping **to** way people communicate with their pets so you always have a snapshot into their day.

**Comment by BrendaHoyle** [comment]
Broken link in Setup Guide page:

<img width="794" alt="setupguide-brokenlink" src="https://cloud.githubusercontent.com/assets/25016008/23387213/386fad46-fd29-11e6-9346-c977aead41a3.png">

**Comment by jammiemountz** [comment]
the grays in the "specs" icons dont match the grays on the rest of the page

**Comment by BrendaHoyle** [comment]
Email should be a link

<img width="428" alt="orderpage-email" src="https://cloud.githubusercontent.com/assets/25016008/23487800/726cc626-feb6-11e6-9bfc-0fa8eb54c012.png">

**Comment by jammiemountz** [comment]
great stuff, thanks @BrendaHoyle !!!
