### ISSUE TITLE
Links

### ISSUE THREAD

**Issue by BrendaHoyle** [jammiemountz/petbot-webapp#21]
**Order page:** email should be linked

<img width="428" alt="orderpage-email" src="https://cloud.githubusercontent.com/assets/25016008/23487839/c4b7d2d6-feb6-11e6-828d-838d5cd86aea.png">

**Comment by BrendaHoyle** [comment]
**Setup Guide page:** broken link

<img width="794" alt="setupguide-brokenlink" src="https://cloud.githubusercontent.com/assets/25016008/23487874/0c4f8be8-feb7-11e6-8e29-8d10436ea2c5.png">

**Comment by jammiemountz** [comment]
thanks for reporting this. for the second example, its a little tricky to make it a WORKING link, but I removed the not-working markup around it at least.
