### ISSUE TITLE
Prelaunch email subscription page shows error even after fixing email

### ISSUE THREAD

**Issue by erikahoyle** [jammiemountz/petbot-webapp#24]
This might not matter at this point but the error message when entering an incorrect format for an email doesn't change

![screen shot 2017-03-04 at 11 58 27 am](https://cloud.githubusercontent.com/assets/14882096/23581843/0a2bfe42-00d2-11e7-8b6e-b97b70b7e7cc.png)

**Comment by jammiemountz** [comment]
hey erika thanks for this, I think I'm just going to retire this page on the next publish, and only show the crowdfunding page.
