### ISSUE TITLE
Test cross browsers

### ISSUE THREAD

**Issue by jammiemountz** [jammiemountz/petbot-webapp#9]
support all the browsers

**Comment by BrendaHoyle** [comment]
**Safari:** Features & Team content extends past website edge when full screen (not a problem on Chrome, Firefox or Opera).

**Comment by BrendaHoyle** [comment]
Safari: 
- Team area content extends past site edge
- "Sell petbot" div does not display the larger image are of petbot

Chrome, Firefox, Opera: 
- Above is not a problem on these browsers.
